Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotalManagmentSystem.Models
{
    /// <summary>
    ///  this class represent room  and status  only
    /// </summary>
    public class Room
    {
        [Key]
        public int RoomID { get; set; }// like 404 ,33,43...
        [Required]
        public bool? IsReseved { get; set; } //true or flse


        /// <summary>
        ///  space for forign key and relationship
        /// </summary>
        
         [Required,ForeignKey("RoomCategorys")]
        public int FK_CategoryID { get; set; }
        public virtual RoomCategory RoomCategorys { get; set; }
        /// //////////////////////////////////
      
      
        public ICollection<RoomAndUser>RoomAndUsers { get; set; }

        public ICollection<RoomAndEmployee> RoomAndEmployees { get; set; }
    }
}

Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HotalManagmentSystem.Models
{
    /// <summary>
    ///  this class represent info about customer info 
    ///  name ,UserBarthDate"age" ,national id
    ///  national id,email,password
    /// </summary>
    public class User
    {

        
        [Key,Required,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserID { get; set; }
        [Required, MinLength(14)]
        public string UserNationalID { get; set; }//national id
        [Required, MaxLength(30)]
        public string UserName{ get; set; }
        [Required, MaxLength(30)]
        public string UserPhone { get; set; }
      
        [Required, Column(TypeName = "date")]
        public DateTime UserBarthDate { get; set; }// yyyy/mm/dd  not take hours
        [Required, DataType(DataType.Password)]
        public string UserPassword { get; set; }
        //user 
        /// <summary>
        ///  space for forign key and relationship
        /// </summary>

        public virtual ICollection<RoomAndUser> RoomAndUsers { get; set; }

    }
}

Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotalSystem.ViewModel;
using HotalManagmentSystem.Models;

namespace HotalSystem.Controllers
{
    public class ReservationController : Controller
    {
        Model context { get; set; }
        public ReservationController()
        {
            context = new Model();
        }
        //[HttpPost]
        public ActionResult Index(int userID)
        {
            User user = context.Users.Where(u => u.UserID == userID).FirstOrDefault();
            ViewBag.user = user;
            List<RoomAndUser> ListOfBookingInfo = context.RoomAndUsers.Where(u => u.FK_UserID == userID).ToList();
            List<string> roomtype = new List<string>();
            List<double> roomprice = new List<double>();
            foreach (RoomAndUser item in ListOfBookingInfo)
            {
                Room room = context.Rooms.Where(r => r.RoomID == item.FK_roomId).FirstOrDefault();
                double price = context.RoomCategorys.Where(c => c.CategoryID == room.FK_CategoryID).Select(r => r.CategoryPrice).FirstOrDefault();
                string type = context.RoomCategorys.Where(c => c.CategoryID == room.FK_CategoryID).Select(r => r.CategoryNumberOfPerson).FirstOrDefault();
                ViewData[$"{room.RoomID}price"] = price;
                ViewData[$"{room.RoomID}type"] = type;


            }

            return View(ListOfBookingInfo);
        }

        // GET: Reservation
        public ActionResult Booking()
        {
            List<RoomCategory> roomcategories = context.RoomCategorys.ToList();
            ViewBag.Roomcategories = roomcategories;
            return View();
        }

        [HttpPost]
        public ActionResult Savebooking(BookingdataViewModel BookingData)
        {
            User user = context.Users.Where(u => u.UserNationalID == BookingData.UserNationalID).FirstOrDefault();
           
            ///bool query2 = context.Users.Where(u => u.UserNationalID == BookingData.UserNationalID).Any();
            if (user == null)
            {
                user = new User();
                user.UserName = BookingData.Username;
                user.UserNationalID = BookingData.UserNationalID;
                user.UserPhone = BookingData.UserPhone;
                user.UserBarthDate = BookingData.UserBarthDate;
                user.UserPassword = BookingData.UserPassword;
                context.Users.Add(user); 
            }
            else
            {
                if (BookingData.UserPassword != user.UserPassword)
                {
                    List<RoomCategory> roomcategories = context.RoomCategorys.ToList();
                    ViewBag.Roomcategories = roomcategories;
                    ViewBag.mss = "Error password please try again";
                    return View("Booking");
                }
            }


            List<RoomAndUser> listOfRoomReserved =context.RoomAndUsers.Where(r=>r.Room.FK_CategoryID== BookingData.CatagoryId).ToList();
            DateTime startData = BookingData.reservationDate;

            DateTime EndData = BookingData.reservationDate.AddDays(BookingData.NumberOfDays-1);
            Dictionary<int, int> ValidFRoomReserved = new Dictionary<int, int>();//filter of RoomAndUser 
       
            foreach (RoomAndUser it in listOfRoomReserved)
            {
                
             int option1= DateTime.Compare(it.reservationDate,EndData);//1//your sart bager than me my end
             int option2 = DateTime.Compare(startData,it.reservationDate.AddDays(it.NumberOfDays-1));//1 my start aftar you
               if (option1>0||option2>0)
               {
                   
                    if(ValidFRoomReserved.ContainsKey(it.FK_roomId)==false )
                          ValidFRoomReserved.Add( it.FK_roomId,1);
               }
               else// unvalid
                {
                   if (ValidFRoomReserved.ContainsKey(it.FK_roomId) == true)
                        ValidFRoomReserved[it.FK_roomId]= 0;
                   else  ValidFRoomReserved.Add(it.FK_roomId, 0);
                }
            }
            HashSet<int> uniquevaild= new HashSet<int>();
            foreach (var it in ValidFRoomReserved)
            {
                if(it.Value==1)
                uniquevaild.Add(it.Key);
            }
           // return Content($"{uniquevaild.Count()}");
            int emptyrooms = context.RoomCategorys.Where(d => d.CategoryID == BookingData.CatagoryId).FirstOrDefault().UnreservedRoomCount;
            if (emptyrooms >= BookingData.NumberOfRoom)
            {
                RoomCategory category = context.RoomCategorys.Where(d => d.CategoryID == BookingData.CatagoryId).FirstOrDefault();
                category.UnreservedRoomCount -= BookingData.NumberOfRoom;
               var unreserved = context.Rooms.Where(r => r.IsReseved == false && r.FK_CategoryID == BookingData.CatagoryId).ToList();
               
                foreach(var item in unreserved)//list of room which is unreserved
                {
                    if (BookingData.NumberOfRoom == 0) break;
                    BookingData.NumberOfRoom--;
                    item.IsReseved = true;//room table
                    //room and user
                    RoomAndUser reservationdata = new RoomAndUser();
                    reservationdata.reservationDate = BookingData.reservationDate;
                    reservationdata.NumberOfDays = BookingData.NumberOfDays;
                    reservationdata.FK_UserID = user.UserID;
                    reservationdata.FK_roomId = item.RoomID;
                    //add
                    context.RoomAndUsers.Add(reservationdata);
                }
                //save
                context.SaveChanges();
                // room id
                return RedirectToAction("Index",new { userID = user.UserID });
            }
           else if (emptyrooms+ uniquevaild.Count()>= BookingData.NumberOfRoom)
            {
                RoomCategory category = context.RoomCategorys.Where(d => d.CategoryID == BookingData.CatagoryId).FirstOrDefault();
                category.UnreservedRoomCount -= emptyrooms;// UnreservedRoomCount=emptyrooms
               List< Room> unreserved = context.Rooms.Where(r => r.IsReseved == false && r.FK_CategoryID == BookingData.CatagoryId).ToList();

                foreach (Room item in unreserved)//list of room which is unreserved
                {
                    if (emptyrooms == 0) break;
                    emptyrooms--;
                    BookingData.NumberOfRoom--;
                    item.IsReseved = true;//room table
                    //room and user
                    RoomAndUser reservationdata = new RoomAndUser();
                    reservationdata.reservationDate = BookingData.reservationDate;
                    reservationdata.NumberOfDays = BookingData.NumberOfDays;
                    reservationdata.FK_UserID = user.UserID;
                    reservationdata.FK_roomId = item.RoomID;
                    //add
                    context.RoomAndUsers.Add(reservationdata);
                }
                foreach (int id in uniquevaild)
                {
                   
                    if (BookingData.NumberOfRoom == 0) break;
                    BookingData.NumberOfRoom--;
                    //room and user
                    RoomAndUser reservationdata = new RoomAndUser();
                    reservationdata.reservationDate = BookingData.reservationDate;
                    reservationdata.NumberOfDays = BookingData.NumberOfDays;
                    reservationdata.FK_UserID = user.UserID;
                    reservationdata.FK_roomId = id;
                    //add
                    context.RoomAndUsers.Add(reservationdata);
                }
                    context.SaveChanges();
                return RedirectToAction("Index", new { userID = user.UserID });
            }
            else
            {
                List<RoomCategory> roomcategories = context.RoomCategorys.ToList();
                ViewBag.Roomcategories = roomcategories;
              int totalRoom=  roomcategories.Where(r => r.CategoryID == BookingData.CatagoryId).Select(n => n.RoomTypeCount).FirstOrDefault();
                if (totalRoom < BookingData.NumberOfRoom)
                {
                    ViewBag.message = ($"this numbber of room  not avalible you can rserve {emptyrooms+uniquevaild.Count()} rooms .");
                    
                }
                else
                {
                    ViewBag.message = (emptyrooms != 0 ? $"You Can't Reserve More Than {emptyrooms} ." : $"We do not have any Room in this date !");
                   
                }
                return View("Booking");
            }
        }
      
    }
}

Controllers/UserController.cs
using HotalManagmentSystem.Models;
using System.Linq;
using System.Web.Mvc;
using System.Collections.Generic;


namespace HotalSystem.Controllers
{
    public class UserController : Controller
    {
        Model context = new Model();

        #region UserEnterface
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateAcount()
        {
            return View();
        }
        public ActionResult SignIn()
        {
            return View();
        }
        public ActionResult Booking()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult services()
        {
            return View();
        }
        public ActionResult Rooms()
        {
            return View();
        }

        #endregion


        // GET: User
        #region user user
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult CheckLogin(string UserNationalID,string UserPassword)
        {
            bool Flag = context.Users.Where(c => c.UserNationalID == UserNationalID).Any();
            if (Flag == false)
            {
                string str = "You Can't Enter";
                ViewBag.message = $" {str} ";
                return View("Login");
            }
            else
            {
                var query1 = context.Users.Where(c => c.UserNationalID == UserNationalID).FirstOrDefault();
                if (query1.UserPassword != UserPassword)
                {
                    string str = "Wrong Password";
                    ViewBag.message = $" {str} ";
                    return View("Login");
                }
                return View(query1);
            }
        }


        public ActionResult Search(int id)
        {
            var query = context.Users.FirstOrDefault(u => u.UserID == id);
            return View(query);
        }

        public ActionResult MoreDetails(int id)
        {
            var query = context.RoomAndUsers.Where(d => d.FK_UserID == id).ToList();
            return View(query);
        }
        
        public ActionResult EditUser(int id)
        {
            var query = context.Users.FirstOrDefault(c => c.UserID == id);
            return View(query);
        }
       [HttpPost]
        public ActionResult SaveEditUser(int id, User newuser)
        {

            if (newuser.UserName != null)
            {
                User Euser = context.Users.FirstOrDefault(c => c.UserID == id);
                Euser.UserName = newuser.UserName;
                Euser.UserNationalID = newuser.UserNationalID;
                Euser.UserPassword = newuser.UserPassword;
                Euser.UserPhone = newuser.UserPhone;
                Euser.UserBarthDate = newuser.UserBarthDate;
                context.SaveChanges();
                return RedirectToAction("CheckLogin",new { UserNationalID=newuser.UserNationalID, UserPassword=newuser.UserPassword });
            }
            else
            {
                var query = context.Users.FirstOrDefault(c => c.UserID == id);
                return View("EditUser", query);
            }

        }
    
        #endregion
       
    }
}

Views/User/Booking.cshtml
@{
    ViewBag.Title = "Booking";
}


<br />
<section>
    <div class="container wow fadeInUp">
        <div class="row">
            <div class="col-md-12">
                <h3 class="section-title">Book Now </h3>
                <div class="section-title-divider"></div>
            </div>
        </div>
    </div>
</section>

<form class="row g-3 border-bottom center-block">

    <div class="container wow fadeInUp">

        <div class="col-md-6">

            <label for="StartDate" class="form-label">StartDate</label>
            <input type="date" class="form-control" id="StartDate">
        </div>
        <br />
        <div class="col-md-6">

            <label for="Diuration" class="form-label">Diuration</label>
            <input type="text" class="form-control" id="Diuration">
        </div>
        <br />
        <div class="col-md-6">
            <select class="form-select ">
                <option selected>Type Of Room </option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </div>
        <br />

        <div class="col-12">
            <button type="submit" class="btn btn-dark">Book Now </button>
        </div>

    </div>
</form>
<br />
<br />

Views/User/CheckLogin.cshtml
@model HotalManagmentSystem.Models.User
@{
    ViewBag.Title = "CheckLogin";
}


<br>
<div class="container wow fadeInUp">
    <div class="row">
        <div class="col-md-12">
            <h3 class="section-title">Show User Details</h3>
            <div class="section-title-divider"></div>
        </div>
    </div>
</div>
<br />
<div class="container wow fadeInUp">
    <div class="row">
        <div class="col-md-4">
            <a href="/User/Search/@Model.UserID" class="btn btn-dark">Search</a>
        </div>
    </div>
</div>
<br />
<div class="container wow fadeInUp">
    <div class="row">
        <div class="col-md-4">
            <a href="/User/EditUser/@Model.UserID" class="btn btn-dark"> Edit Profiel  </a>
        </div>
    </div>
</div>
<br />
<div class="container wow fadeInUp">
    <div class="row">
        <div class="col-md-4">
            <a href="/EditReservation/Show/@Model.UserID" class="btn btn-dark">Edit  Reservetion  </a>
        </div>
    </div>
</div>
<br />
<br />
<div class="container wow fadeInUp">
    <div class="row">
        <div class="col-md-4">
            <a href="/CancelRerservation/ShowRooms/@Model.UserID" class="btn btn-dark">Cancel  Reservetion Room  </a>
        </div>
    </div>
</div>
<br />
<br />

Views/User/CreateAcount.cshtml
@{
    ViewBag.Title = "CreateAcount";
}

<br />
<br />

<section>
    <div class="container wow fadeInUp">
        <div class="row">
            <div class="col-md-12">
                <h3 class="section-title">Create Acount</h3>
                <div class="section-title-divider"></div>
            </div>
        </div>
    </div>
</section>

<form class="row g-3 border-bottom center-block">

    <div class="container wow fadeInUp">

        <div class="col-md-6">

            <label for="Name" class="form-label">Name</label>
            <input type="text" class="form-control" id="Name">
        </div>

        <div class="col-md-6">

            <label for="Email" class="form-label">Email</label>
            <input type="email" class="form-control" id="Email">
        </div>


        <div class="col-md-6">
            <label for="inputPassword4" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputPassword4">
        </div>

        <div class="col-md-6">
            <label for="inputPassword4" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="inputPassword4">
        </div>
        <br />
        <div class="col-12">
            <button type="submit" class="btn btn-dark">Create New Acount</button>
        </div>
        <div class="col-12">
            <br />
            <h4>
                Already have an account?   <a href="/User/SignIn"> Sign In  </a>
            </h4>

        </div>
    </div>
</form>

Views/User/DetailsAboutOneUser.cshtml
@using HotalManagmentSystem.Models
@model List<HotalManagmentSystem.Models.RoomAndUser>
@{
    ViewBag.Title = "DetailsAboutOneUser";
}


<br>
<div class="container wow fadeInUp">
    <div class="row">
        <div class="col-md-12">
            <h3 class="section-title">Details Of Booking Room</h3>
            <div class="section-title-divider"></div>
        </div>
    </div>
</div>

<br />

<!--<html>
<head>-->
<!-- this meta for coding -->
<!--<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        table, th, td {
            text-align: center border: 5px solid black;
            /*border-collapse: collapse;*/
        }

        table {
            border-spacing: 5px;
        }
    </style>
</head>
<bode>
    <table class="table table-dark table-sm" style="width: 100%;">

        <th>UserID</th>
        <th>reservationDate</th>
        <th>NumberOfDays</th>
        <th>DiedLineOfRoom</th>
        <th>RoomID</th>
        <tr>

            @foreach (var item in Model)
            {
            <tr>
                <td rowspan="@item">@item.FK_UserID</td>
                <td rowspan="@item">@item.reservationDate.ToString("dd-MM-yyyy")</td>
                <td rowspan="@item">@item.NumberOfDays</td>
                <td rowspan="@item">@item.reservationDate.AddDays(item.NumberOfDays).ToString("dd-MM-yyyy")</td>
                <td rowspan="@item">@item.FK_roomId</td>
            </tr>

        }
            </tr>

        </table>
        <br />
        <td><p><a href="/User/ShowUsersDetils" class="btn btn-success">Back To List</a></p></td>

    </bode>
</html>-->
<table class="table">
<thead class="table-dark">
    <tr>
        <th>UserID</th>
        <th>reservationDate</th>
        <th>NumberOfDays</th>
        <th>DiedLineOfRoom</th>
        <th>RoomID</th>
    </tr>
</thead>
<tbody>
    <tr>
        @foreach (var item in Model)
        {
            <tr>
                <td rowspan="@item">@item.FK_UserID</td>
                <td rowspan="@item">@item.reservationDate.ToString("dd-MM-yyyy")</td>
                <td rowspan="@item">@item.NumberOfDays</td>
                <td rowspan="@item">@item.reservationDate.AddDays(item.NumberOfDays).ToString("dd-MM-yyyy")</td>
                <td rowspan="@item">@item.FK_roomId</td>
            </tr>
        }
    </tr>
    <tr>
        <td><p><a href="/User/ShowUsersDetils" class="btn btn-dark">Back To List</a></p></td>
    </tr>

</tbody>
</table>    

Views/User/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!-- ======= Hero Section ======= -->
<body>
    <section id="hero">
        <div class="hero-container">
            <div class="wow fadeIn">
                <div class="hero-logo">
                    <img class="" src="~/Content/assets/img/logo.png" alt="Imperial">
                </div>

                <h1>Welcome to Imperial Hotel</h1>
                <h2>We Provides <span class="typed" data-typed-items=" Comfortable Rooms , beautiful Views, , Exciting Services"></span></h2>
                <div class="actions">

                    <a onclick="location.href='@Url.Action("Booking","Reservation")'" class="btn-get-started"> Book Now </a>
                    <a onclick="location.href='@Url.Action("Login","User")'" class="btn-get-started"> Login </a>

                </div>
            </div>
        </div>
    </section><!-- End Hero -->
    <!-- ======= Portfolio Section ======= -->
   
    <section id="portfolio">
        <div class="container wow fadeInUp">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="section-title">Portfolio</h3>
                    <div class="section-title-divider"></div>
                    <p class="section-description">Si stante, hoc natura videlicet vult, salvam esse se, quod concedimus ses haec dicturum fuisse</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 d-flex justify-content-center">
                    <ul id="portfolio-flters">
                        <li data-filter="*" class="filter-active">All</li>
                        <li data-filter=".filter-app">One Person</li>
                        <li data-filter=".filter-card">Two Person</li>
                        <li data-filter=".filter-web">Reception</li>
                    </ul>
                </div>
            </div>

            <div class="row portfolio-container">

                <div class="col-lg-4 col-md-6 portfolio-item filter-app">
                    <img src="~/Content/assets/img/portfolio/a1.jpg" class="img-fluid" alt="">
                    <div class="portfolio-info">
                        <h4>One Person</h4>
                        <p>One Person</p>
                        <a href="~/Content/assets/img/portfolio/a1.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="App 1"><i class="fa fa-plus"></i></a>
                        <a href="/RoomCategories/ShowAllCategoryDetails" class="details-link" title="More Details"><i class="fa fa-link fa-flip-horizontal"></i></a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 portfolio-item filter-web">
                    <img src="~/Content/assets/img/portfolio/c1.jpg" class="img-fluid" alt="">
                    <div class="portfolio-info">
                        <h4>Reception</h4>
                        <p>Reception</p>
                        <a href="~/Content/assets/img/portfolio/c1.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Web 3"><i class="fa fa-plus"></i></a>
                        <a href="/RoomCategories/ShowAllCategoryDetails" class="details-link" title="More Details"><i class="fa fa-link fa-flip-horizontal"></i></a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 portfolio-item filter-app">
                    <img src="~/Content/assets/img/portfolio/a2.jpg" class="img-fluid" alt="">
                    <div class="portfolio-info">
                        <h4>One Person</h4>
                        <p>One Person</p>
                        <a href="~/Content/assets/img/portfolio/a2.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="App 2"><i class="fa fa-plus"></i></a>
                        <a href="/RoomCategories/ShowAllCategoryDetails" class="details-link" title="More Details"><i class="fa fa-link fa-flip-horizontal"></i></a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 portfolio-item filter-card">
                    <img src="~/Content/assets/img/portfolio/b1.jpg" class="img-fluid" alt="">
                    <div class="portfolio-info">
                        <h4>Two Person</h4>
                        <p>Two Person</p>
                        <a href="~/Content/assets/img/portfolio/b1.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Card 2"><i class="fa fa-plus"></i></a>
                        <a href="/RoomCategories/ShowAllCategoryDetails" class="details-link" title="More Details"><i class="fa fa-link fa-flip-horizontal"></i></a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 portfolio-item filter-web">
                    <img src="~/Content/assets/img/portfolio/c2.jpg" class="img-fluid" alt="">
                    <div class="portfolio-info">
                        <h4>Reception</h4>
                        <p>Reception</p>
                        <a href="~/Content/assets/img/portfolio/c2.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Web 2"><i class="fa fa-plus"></i></a>
                        <a href="/RoomCategories/ShowAllCategoryDetails" class="details-link" title="More Details"><i class="fa fa-link fa-flip-horizontal"></i></a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 portfolio-item filter-app">
                    <img src="~/Content/assets/img/portfolio/a3.jpg" class="img-fluid" alt="">
                    <div class="portfolio-info">
                        <h4>One Person</h4>
                        <p>One Person</p>
                        <a href="~/Content/assets/img/portfolio/a3.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="App 3"><i class="fa fa-plus"></i></a>
                        <a href="/RoomCategories/ShowAllCategoryDetails" class="details-link" title="More Details"><i class="fa fa-link fa-flip-horizontal"></i></a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 portfolio-item filter-card">
                    <img src="~/Content/assets/img/portfolio/b2.jpg" class="img-fluid" alt="">
                    <div class="portfolio-info">
                        <h4>Two Person</h4>
                        <p>Two Person</p>
                        <a href="~/Content/assets/img/portfolio/b2.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Card 1"><i class="fa fa-plus"></i></a>
                        <a href="/RoomCategories/ShowAllCategoryDetails" class="details-link" title="More Details"><i class="fa fa-link fa-flip-horizontal"></i></a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 portfolio-item filter-card">
                    <img src="~/Content/assets/img/portfolio/b3.jpg" class="img-fluid" alt="">
                    <div class="portfolio-info">
                        <h4>Two Person</h4>
                        <p>Two Person</p>
                        <a href="~/Content/assets/img/portfolio/b3.jpg" data3-gall="portfolioGallery" class="venobox preview-link" title="Card 3"><i class="fa fa-plus"></i></a>
                        <a href="/RoomCategories/ShowAllCategoryDetails" class="details-link" title="More Details"><i class="fa fa-link fa-flip-horizontal"></i></a>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 portfolio-item filter-web">
                    <img src="~/Content/assets/img/portfolio/c3.jpg" class="img-fluid" alt="">
                    <div class="portfolio-info">
                        <h4>Reception</h4>
                        <p>Reception</p>
                        <a href="~/Content/assets/img/portfolio/c3.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Web 3"><i class="fa fa-plus"></i></a>
                        <a href="/RoomCategories/ShowAllCategoryDetails" class="details-link" title="More Details"><i class="fa fa-link fa-flip-horizontal"></i></a>
                    </div>
                </div>

            </div>

        </div>
    </section>
</body>

Views/User/Login.cshtml
@using HotalManagmentSystem.Models;
@{
    ViewBag.Title = "Login";
}

<br>
<div class="container wow fadeInUp">
    <div class="row">
        <div class="col-md-12">
            <h3 class="section-title">Login</h3>
            <div class="section-title-divider"></div>
        </div>
    </div>
</div>

<br />

<form class="row g-3 border-bottom center-block" action="/User/CheckLogin" method="post">

    <div class="container wow fadeInUp">
        <div>
            <label for="">National Id</label>
            <input type="text"
                   name="UserNationalID"
                   class="form-control"
                   required>

        </div>
        <div>
            <label for="">Password</label>
            <input type="password"
                   name="UserPassword"
                   class="form-control"
                   required>
           @if (ViewBag.message != null)
            {
                <span class="text-danger">@ViewBag.message</span>
            }
        </div>
       
        <br />
        <button type="submit" class="btn btn-dark">Enter</button>
        <br />
    </div>
</form>
<br />

Views/User/Rooms.cshtml
@{
    ViewBag.Title = "Rooms";
}
<body>
    <div style="width:500px  auto ;height:100px auto">
        <section id="hero">
            <div class="hero-container ">
                <div class="hero-logo">
                    <img class="" src="~/Content/assets/img/logo.png" alt="Imperial">
                </div>

                <h1>Welcome to Imperial Hotel</h1>
                <div class="wow fadeIn">
                    <h2><span class="typed" data-typed-items="Our Rooms"></span></h2>
                </div>
            </div>
        </section>
    </div>
































</body>